---
- name: install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - gcc
    - make
    - libc6-dev
  when: ansible_os_family == "Debian"
  tags: install

- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - make
  when: ansible_os_family == "RedHat"
  tags: install
  
- name: install dependencies
  zypper: name={{ item }} state=present
  with_items:
    - gcc
    - make
  when: ansible_os_family == 'Suse'
  tags: install


- name: enable overcommit in sysctl
  sysctl: name=vm.overcommit_memory value=1 state=present reload=yes ignoreerrors=yes
  when: redis_travis_ci is not defined
  tags: install


- name: download redis
  get_url: url=http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
           dest=/usr/local/src/redis-{{ redis_version }}.tar.gz
  when: not redis_tarball
  tags: install

- name: upload redis
  copy: src={{ redis_tarball }}
        dest=/usr/local/src/redis-{{ redis_version }}.tar.gz  
  when: redis_tarball
  tags: install


- name: extract redis tarball
  shell: tar xf /usr/local/src/redis-{{ redis_version }}.tar.gz -C /usr/local/src
         creates=/usr/local/src/redis-{{ redis_version }}
  tags: install
         
- name: compile redis
  command: make -j5
           chdir=/usr/local/src/redis-{{ redis_version }}
           creates=/usr/local/src/redis-{{ redis_version }}/src/redis-server
  tags: install

          
- name: create redis install directory
  file: path={{ redis_install_dir }} state=directory
  tags: install
  
- name: create /etc/redis
  file: path=/etc/redis state=directory
  tags: install
  
- name: add redis user
  user:
    name={{ redis_user }}
    comment="Redis"
    home={{ redis_install_dir }}
    shell=/bin/false
    system=yes
  tags: install
  
- name: create /var/run/redis
  file: path=/var/run/redis state=directory
        owner={{ redis_user }}
  tags: install
- name: install redis
  command: make PREFIX={{ redis_install_dir }} install
           chdir=/usr/local/src/redis-{{ redis_version }}
           creates={{ redis_install_dir }}/bin/redis-server
  tags: install