---
- include: install.yml
  tags:
    - install
- include: server.yml
  when: not redis_sentinel
  tags:
    - config
- include: sentinel.yml
  when: redis_sentinel
  tags:
    - config
- include: local_facts.yml